//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarInsuranceQuotes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteVariable
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<short> CarYear { get; set; }
        public string CarMake { get; set; }
        public string CarModel { get; set; }
        public Nullable<bool> DUI { get; set; }
        public Nullable<short> SpeedingTickets { get; set; }
        public Nullable<bool> CoverageType { get; set; }

        //[DisplayFormat(DataFormatString = "{0:c}")]
        public Nullable<decimal> TotalCost { get; set; }
    }
}
